# Visualizations
This notebook is intended to demonstrate what can be done with scraped and converted JSON files retrieved in Step1, Step2, and Step3 notebooks. In this notebook, I load in dataframes created and cleaned in data_cleaning.ipynb, then plot and save interactive charts of different fanwork metadata features in my dataset using plotly.express.

At the start of this project, I had intended to build a fanwork metadata dashboard using Streamlit Community Cloud. That plan proved too ambitious for the scope of this quarter, but creating a fanwork metadata dashboard using this project as a basis is an eventual goal of mine. This visualizations notebook would be a foundational part of such a project.

In [1]:
# import libraries
import pandas as pd
import plotly.express as px

## Read in Dataframes

In [2]:
# read in cleaned overall dataframe
cleaned_candela_df = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/cleaned_candela_df.csv')

# read in exploded dataframes
df_characters = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/character_df_exploded.csv')
df_relationships = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/relationships_df_exploded.csv')
df_fandom = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/fandom_df_exploded.csv')
df_warnings = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/warnings_df_exploded.csv')
df_additional = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/additional_tags_df_exploded.csv')
df_categories = pd.read_csv('/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/csv_files/categories_df_exploded.csv')

In [3]:
print(len(cleaned_candela_df))
print(len(df_characters))
print(len(df_relationships))
print(len(df_fandom))
print(len(df_warnings))
print(len(df_additional))
print(len(df_categories))

211
801
353
211
199
2273
211

In [4]:
display(cleaned_candela_df)

,Unnamed: 0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"['Malcolm Trills', 'Leo Amicus', 'Grimoria (Ca...",Leo Amicus & Malcolm Trills,"['Team as Family', 'Team Dynamics', 'Affection...",English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371
1,1,2,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"['Grimoria', 'Malcolm Trills', 'Decklan Murphy...",Grimoria & Malcolm Trills,"['Pre-Canon', 'someone give this girl a hug', ...",English,2024-03-02 00:00:00,2024-03-02 00:00:00,1067,1/1,3,36,1,290
2,2,3,Explicit,"['Graphic Depictions Of Violence, Major Charac...",F/M,Candela Obscura (Critical Role Web Series),"['Sean Finnerty (Candela Obscura)', 'Marion Co...",['Sean Finnerty (Candela Obscura) & Original C...,"['Angst', 'Hurt', 'Hurt No Comfort', 'Hurt/Com...",English,Unknown,2024-02-27 00:00:00,8013,NaN,3,10,3,160
3,3,4,Explicit,"['Graphic Depictions Of Violence, Major Charac...",F/M,Candela Obscura (Critical Role Web Series),"['Sean Finnerty (Candela Obscura)', 'Marion Co...",['Sean Finnerty (Candela Obscura) & Original C...,"['Angst', 'Hurt', 'Hurt No Comfort', 'Hurt/Com...",English,Unknown,2024-02-27 00:00:00,8013,NaN,3,10,3,160
4,4,5,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Elsie Roberts (Candela Obscura)', 'Oscar Gri...","['Rajan Savarimuthu/Original character', 'Form...","['Murder Mystery', 'Arson', 'Disability', 'Can...",English,2024-02-25 00:00:00,2024-02-25 00:00:00,46890,28/28,28,7,2,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,7,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),['Arlo Black (Candela Obscura)'],No relationships tagged,['Character Study'],English,2023-07-04 00:00:00,2023-07-04 00:00:00,2129,1/1,5,53,7,310
207,207,8,Explicit,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'August James...",August 'Auggie' James/ Arlo Black,['Ftm August James'],English,Unknown,2023-07-03 00:00:00,6125,NaN,9,83,8,1259
208,208,9,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'August ""Augg...","Arlo Black/August ""Auggie"" James","['Written post episode 2', 'First Kiss', 'Idk ...",English,2023-07-02 00:00:00,2023-07-02 00:00:00,3378,1/1,48,332,49,1670
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'Howard Margr...","['Arlo Black & Howard Margrove', 'Arlo Black/H...","['missing interlude', ""Blink and you'll miss i...",English,2023-06-26 00:00:00,2023-06-26 00:00:00,1082,1/1,2,27,4,220
210,210,11,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,['Arlo Black'],No relationships tagged,['Character Study'],English,2023-05-26 00:00:00,2023-05-26 00:00:00,1129,1/1,12,67,2,461

## Bar Charts: "Most Commonly Tagged"

### Most Commonly Tagged Characters

In [5]:
# answers question: which characters are most represented?
# top 10 characters
character_counts = df_characters['Characters'].value_counts()
df_character_counts = character_counts.to_frame().reset_index()
df_character_counts = df_character_counts.sort_values(by='count', ascending=False)
df_character_counts[0:10]

                    Characters  count
0                Sean Finnerty     89
1               Marion Collodi     87
2            Rajan Savarimuthu     70
3                Elsie Roberts     66
4              Nathaniel Trapp     55
5      Dr. Jinnah "Jean" Basar     46
6          Original Characters     39
7                  Cosmo Grimm     31
8  Beatrix Monroe | Auntie Bee     30
9                  Oscar Grimm     30

In [6]:
# plot top 10 characters
labels = {'Characters':'Character', 'count':'Number of times tagged'}
fig = px.bar(df_character_counts[0:10], x="count", y="Characters", labels=labels, title='Most Commonly Tagged Characters')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/most_common_characters.html")

### Most Commonly Tagged Relationships

In [7]:
# answers question: which relationships are most represented?
relationship_counts = df_relationships['Relationships'].value_counts()
df_relationship_counts = relationship_counts.to_frame().reset_index()
df_relationship_counts = df_relationship_counts.sort_values(by='count', ascending=False)
df_relationship_counts[0:10]

                                      Relationships  count
0                   Elsie Roberts/Rajan Savarimuthu     47
1                    Marion Collodi & Sean Finnerty     24
2                      Marion Collodi/Sean Finnerty     23
3                           No relationships tagged     20
4                      Sean Finnerty/Marion Collodi     13
5           Rajan Savarimuthu/Original Character(s)     12
6                                Former Rajan/Elsie     12
7  Jinnah "Jean" Basar/Marion Collodi/Sean Finnerty     12
8               Jinnah "Jean" Basar & Sean Finnerty     11
9             Sean Finnerty & Original Character(s)     10

In [8]:
# plotly bar chart
labels = {'Relationships':'Relationships', 'count':'Number of times tagged'}
fig = px.bar(df_relationship_counts[0:10], x="count", y="Relationships", labels=labels, title='Most Commonly Tagged Relationships')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/most_common_relationships.html")

### Most Commonly Tagged Categories

In [9]:
display(df_categories)

,Unnamed: 0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"['Malcolm Trills', 'Leo Amicus', 'Grimoria (Ca...",Leo Amicus & Malcolm Trills,"['Team as Family', 'Team Dynamics', 'Affection...",English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371
1,1,2,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"['Grimoria', 'Malcolm Trills', 'Decklan Murphy...",Grimoria & Malcolm Trills,"['Pre-Canon', 'someone give this girl a hug', ...",English,2024-03-02 00:00:00,2024-03-02 00:00:00,1067,1/1,3,36,1,290
2,2,3,Explicit,"['Graphic Depictions Of Violence, Major Charac...",F/M,Candela Obscura (Critical Role Web Series),"['Sean Finnerty (Candela Obscura)', 'Marion Co...",['Sean Finnerty (Candela Obscura) & Original C...,"['Angst', 'Hurt', 'Hurt No Comfort', 'Hurt/Com...",English,Unknown,2024-02-27 00:00:00,8013,NaN,3,10,3,160
3,3,4,Explicit,"['Graphic Depictions Of Violence, Major Charac...",F/M,Candela Obscura (Critical Role Web Series),"['Sean Finnerty (Candela Obscura)', 'Marion Co...",['Sean Finnerty (Candela Obscura) & Original C...,"['Angst', 'Hurt', 'Hurt No Comfort', 'Hurt/Com...",English,Unknown,2024-02-27 00:00:00,8013,NaN,3,10,3,160
4,4,5,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Elsie Roberts (Candela Obscura)', 'Oscar Gri...","['Rajan Savarimuthu/Original character', 'Form...","['Murder Mystery', 'Arson', 'Disability', 'Can...",English,2024-02-25 00:00:00,2024-02-25 00:00:00,46890,28/28,28,7,2,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,7,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),['Arlo Black (Candela Obscura)'],No relationships tagged,['Character Study'],English,2023-07-04 00:00:00,2023-07-04 00:00:00,2129,1/1,5,53,7,310
207,207,8,Explicit,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'August James...",August 'Auggie' James/ Arlo Black,['Ftm August James'],English,Unknown,2023-07-03 00:00:00,6125,NaN,9,83,8,1259
208,208,9,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'August ""Augg...","Arlo Black/August ""Auggie"" James","['Written post episode 2', 'First Kiss', 'Idk ...",English,2023-07-02 00:00:00,2023-07-02 00:00:00,3378,1/1,48,332,49,1670
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'Howard Margr...","['Arlo Black & Howard Margrove', 'Arlo Black/H...","['missing interlude', ""Blink and you'll miss i...",English,2023-06-26 00:00:00,2023-06-26 00:00:00,1082,1/1,2,27,4,220
210,210,11,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,['Arlo Black'],No relationships tagged,['Character Study'],English,2023-05-26 00:00:00,2023-05-26 00:00:00,1129,1/1,12,67,2,461

In [10]:
# plot distribution of categories
category_counts = df_categories['Category'].value_counts()
df_categories = category_counts.to_frame().reset_index()
df_categories = df_categories.sort_values(by='count', ascending=False)

In [11]:
print(df_categories)

               Category  count
0                   F/M     67
1                   Gen     51
2                   M/M     50
3  No categories tagged     26
4   Multiple Categories      9
5                 Multi      7
6                   F/F      1

In [12]:
# plotly bar chart
labels = {'Category':'Category', 'count':'Number of times tagged'}
fig = px.bar(df_categories, x="count", y="Category", labels=labels, title='Most Commonly Tagged Categories')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/most_common_categories.html")

### Most Commonly Tagged Archive Warnings

In [13]:
# answers: which archive warnings are most represented?
warning_counts = df_warnings['Archive Warnings'].value_counts()
df_warning_counts = warning_counts.to_frame().reset_index()
df_warning_counts = df_warning_counts.sort_values(by='count', ascending=False)

In [14]:
print(df_warning_counts)

                            Archive Warnings  count
0                  No Archive Warnings Apply    128
1             Graphic Depictions Of Violence     39
2  Creator Chose Not To Use Archive Warnings     21
3                      Major Character Death     11

In [15]:
# plotly bar chart
labels = {'Archive Warnings':'Archive Warning', 'count':'Number of times tagged'}
fig = px.bar(df_warning_counts, x="count", y="Archive Warnings", labels=labels, title='Most Commonly Tagged Archive Warnings')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/most_common_warnings.html")

### Most Common Additional Tags

In [16]:
# which ratings are most represented?
additional_counts = df_additional['Additional Tags'].value_counts()
df_additional_counts = additional_counts.to_frame().reset_index()
df_additional_counts = df_additional_counts.sort_values(by='count', ascending=False)
df_additional_counts[0:10]

                                 Additional Tags  count
0                                          Angst     44
1                                   Hurt/Comfort     42
2                                    Body Horror     42
3      Circle of Tide and Bone (Candela Obscura)     33
4                          Dead Dove: Do Not Eat     30
5                         Canon-Typical Violence     30
6                                  Not Beta Read     25
7  Circle of Needle and Thread (Candela Obscura)     25
8                         Emotional Hurt/Comfort     23
9                                      Pre-Canon     22

In [18]:
# plotly bar chart
labels = {'Additional Tags':'Freeform Tag', 'count':'Number of times tagged'}
fig = px.bar(df_additional_counts[0:10], x="count", y="Additional Tags", labels=labels, title='Most Frequent Freeform Tags')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/most_common_freeform_tags.html")

### Most Common Ratings

In [19]:
# which ratings are most represented?
rating_counts = cleaned_candela_df['Rating'].value_counts()
df_rating_counts = rating_counts.to_frame().reset_index()
df_rating_counts = df_rating_counts.sort_values(by='count', ascending=False)

In [20]:
print(df_rating_counts)

                  Rating  count
0  Teen And Up Audiences     78
1               Explicit     45
2              Not Rated     36
3                 Mature     33
4      General Audiences     19

In [21]:
# plotly bar chart
labels = {'Rating':'Rating', 'count':'Number of times tagged'}
fig = px.bar(df_rating_counts, x="count", y="Rating", labels=labels, title='Most Commonly Tagged Archive Ratings')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/most_common_ratings.html")

## Scatterplots: Impact of Word Count on Reader Engagement

In [22]:
display(cleaned_candela_df)

,Unnamed: 0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"['Malcolm Trills', 'Leo Amicus', 'Grimoria (Ca...",Leo Amicus & Malcolm Trills,"['Team as Family', 'Team Dynamics', 'Affection...",English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371
1,1,2,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"['Grimoria', 'Malcolm Trills', 'Decklan Murphy...",Grimoria & Malcolm Trills,"['Pre-Canon', 'someone give this girl a hug', ...",English,2024-03-02 00:00:00,2024-03-02 00:00:00,1067,1/1,3,36,1,290
2,2,3,Explicit,"['Graphic Depictions Of Violence, Major Charac...",F/M,Candela Obscura (Critical Role Web Series),"['Sean Finnerty (Candela Obscura)', 'Marion Co...",['Sean Finnerty (Candela Obscura) & Original C...,"['Angst', 'Hurt', 'Hurt No Comfort', 'Hurt/Com...",English,Unknown,2024-02-27 00:00:00,8013,NaN,3,10,3,160
3,3,4,Explicit,"['Graphic Depictions Of Violence, Major Charac...",F/M,Candela Obscura (Critical Role Web Series),"['Sean Finnerty (Candela Obscura)', 'Marion Co...",['Sean Finnerty (Candela Obscura) & Original C...,"['Angst', 'Hurt', 'Hurt No Comfort', 'Hurt/Com...",English,Unknown,2024-02-27 00:00:00,8013,NaN,3,10,3,160
4,4,5,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Elsie Roberts (Candela Obscura)', 'Oscar Gri...","['Rajan Savarimuthu/Original character', 'Form...","['Murder Mystery', 'Arson', 'Disability', 'Can...",English,2024-02-25 00:00:00,2024-02-25 00:00:00,46890,28/28,28,7,2,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,7,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),['Arlo Black (Candela Obscura)'],No relationships tagged,['Character Study'],English,2023-07-04 00:00:00,2023-07-04 00:00:00,2129,1/1,5,53,7,310
207,207,8,Explicit,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'August James...",August 'Auggie' James/ Arlo Black,['Ftm August James'],English,Unknown,2023-07-03 00:00:00,6125,NaN,9,83,8,1259
208,208,9,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'August ""Augg...","Arlo Black/August ""Auggie"" James","['Written post episode 2', 'First Kiss', 'Idk ...",English,2023-07-02 00:00:00,2023-07-02 00:00:00,3378,1/1,48,332,49,1670
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"['Arlo Black (Candela Obscura)', 'Howard Margr...","['Arlo Black & Howard Margrove', 'Arlo Black/H...","['missing interlude', ""Blink and you'll miss i...",English,2023-06-26 00:00:00,2023-06-26 00:00:00,1082,1/1,2,27,4,220
210,210,11,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,['Arlo Black'],No relationships tagged,['Character Study'],English,2023-05-26 00:00:00,2023-05-26 00:00:00,1129,1/1,12,67,2,461

### Number of Kudos Received by Word Count

In [24]:
# helps answer: does word count have any impact on the number of kudos an author recieves?
# plotly scatterplot
labels = {'Word Count':'Word Count','Kudos Count':'Number of kudos received'}

fig = px.scatter(cleaned_candela_df, x="Word Count", y="Kudos Count", labels=labels, title='Number of Kudos Received by Word Count')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/word_count_kudos.html")

### Number of Comments Received by Word Count

In [25]:
# helps answer: does word count have any impact on the number of comments an author recieves?
# plotly scatterplot
labels = {'Word Count':'Word Count','Comment Count':'Number of comments received'}
fig = px.scatter(cleaned_candela_df, x="Word Count", y="Comment Count", labels=labels, title='Number of Comments Received by Word Count')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/word_count_comments.html")

### Number of Hits by Word Count

In [26]:
# helps answer: does word count have any impact on hits?
# plotly scatterplot
labels = {'Word Count':'Word Count','Hits Count':'Number of hits'}
fig = px.scatter(cleaned_candela_df, x="Word Count", y="Hits Count", labels=labels, title='Number of Hits by Word Count')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/word_count_hits.html")

### Number of Bookmarks Received by Word Count

In [28]:
# helps answer: does word count have any impact on number of bookmarks?
# plotly scatterplot
labels = {'Word Count':'Word Count','Bookmarks Count':'Number of bookmarks'}
fig = px.scatter(cleaned_candela_df, x="Word Count", y="Bookmarks Count", labels=labels, title='Number of Bookmarks by Word Count')
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/word_count_bookmarks.html")

In [ ]:
# plotly scatterplot
labels = {'Word Count':'Word Count','Comment Count':'Comment Count'}
fig = px.scatter(cleaned_candela_df, x="Word Count", y="Comment Count", labels=labels, title='Word count by comment count')
fig.show()

## Histograms: Distributions

### Distribution of Fanworks Published Over Time

In [ ]:
# how many fics have been published over time?

In [29]:
date_published_unknown = cleaned_candela_df[cleaned_candela_df['Date Published'] == 'Unknown']
print(len(date_published_unknown))

114

In [30]:
date_published_known = cleaned_candela_df[cleaned_candela_df['Date Published'] != 'Unknown']
print(len(date_published_known))

97

In [31]:
date_updated_known = cleaned_candela_df[cleaned_candela_df['Date Updated'] != 'Unknown']
print(len(date_updated_known))

211

In [33]:
# plot date updated histogram
fig = px.histogram(cleaned_candela_df, x="Date Updated", title="Distribution: Date Last Updated")
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/distribution_date_updated.html")

### Distribution of Word Count

In [34]:
# plot distribution of word count
fig = px.histogram(cleaned_candela_df, x="Word Count", title="Distribution: Word Count")
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/distribution_word_count.html")

### Distribution of Comment Count

In [35]:
# plot distribution of comment count
fig = px.histogram(cleaned_candela_df, x="Comment Count", title="Distribution: Comment Count")
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/distribution_comment_count.html")

### Distribution of Bookmarks Count

In [36]:
# plot distribution of bookmarks count
fig = px.histogram(cleaned_candela_df, x="Bookmarks Count", title="Distribution: Bookmarks Count")
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/distribution_bookmarks_count.html")

### Distribution of Kudos Count

In [37]:
# plot distribution of kudos count
fig = px.histogram(cleaned_candela_df, x="Kudos Count", title="Distribution: Kudos Count")
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/distribution_kudos_count.html")

### Distribution of Hits Count

In [38]:
# plot distribution of hits count
fig = px.histogram(cleaned_candela_df, x="Hits Count", title="Distribution: Hits Count")
fig.show()
fig.write_html("/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/assets/visualizations/distribution_hits_count.html")

# Summary
These visualizations are just a sample of what I (and others!) can do with Ao3MM and having access to Ao3 metadata in a JSON format.
In the future, I plan to refine my code and build out a streamlit-based dashboard that folks can replicate for continued fandom meta analysis enjoyment and interest. :)