# Data Cleaning

In [2]:
import pandas as pd
import json

In [33]:
filepath_list = ['/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page1.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page2.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page3.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page4.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page5.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page7.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page8.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page9.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page10.json',
                 '/home/ekmys/PycharmProjects/IMT542_FinalProject_Stelter/data/json_files/candela_page11.json']

In [38]:
# read in and concatenate dataframes
frames_list = []
for i in range(len(filepath_list)):
    df = pd.read_json(filepath_list[i])
    df = df.T
    frames_list.append(df)

In [35]:
print(len(frames_list))

10

In [57]:
candela_df = pd.concat(frames_list)

In [58]:
candela_df = candela_dataframe.reset_index()

In [60]:
display(candela_df)

,level_0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"[Malcolm Trills, Leo Amicus, Grimoria (Candela...",Leo Amicus & Malcolm Trills,"[Team as Family, Team Dynamics, Affectionate I...",\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
1,1,2,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"[Grimoria, Malcolm Trills, Decklan Murphy (Men...",Grimoria & Malcolm Trills,"[Pre-Canon, someone give this girl a hug, The ...",\n English\n,2024-03-02,Unknown,1067,1/1,3,36,1,290
2,2,3,Explicit,"[Graphic Depictions Of Violence, Major Charact...",F/M,Candela Obscura (Critical Role Web Series),"[Sean Finnerty (Candela Obscura), Marion Collo...",[Sean Finnerty (Candela Obscura) & Original Ch...,"[Angst, Hurt, Hurt No Comfort, Hurt/Comfort, E...",English,Unknown,27 Feb 2024,8013,None,3,10,3,160
3,3,4,Explicit,"[Graphic Depictions Of Violence, Major Charact...",F/M,Candela Obscura (Critical Role Web Series),"[Sean Finnerty (Candela Obscura), Marion Collo...",[Sean Finnerty (Candela Obscura) & Original Ch...,"[Angst, Hurt, Hurt No Comfort, Hurt/Comfort, E...",English,Unknown,27 Feb 2024,8013,None,3,10,3,160
4,4,5,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"[Elsie Roberts (Candela Obscura), Oscar Grimm,...","[Rajan Savarimuthu/Original character, Former ...","[Murder Mystery, Arson, Disability, Canon Disa...",\n English\n,2024-02-25,2024-02-25,46890,28/28,28,7,2,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,7,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),[Arlo Black (Candela Obscura)],No relationships tagged,[Character Study],\n English\n,2023-07-04,Unknown,2129,1/1,5,53,7,310
207,207,8,Explicit,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"[Arlo Black (Candela Obscura), August James (C...",August 'Auggie' James/ Arlo Black,[Ftm August James],English,Unknown,03 Jul 2023,6125,None,9,83,8,"1,259"
208,208,9,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"[Arlo Black (Candela Obscura), August ""Auggie""...","Arlo Black/August ""Auggie"" James","[Written post episode 2, First Kiss, Idk they ...",\n English\n,2023-07-02,Unknown,3378,1/1,48,332,49,1670
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),"[Arlo Black (Candela Obscura), Howard Margrove...","[Arlo Black & Howard Margrove, Arlo Black/Howa...","[missing interlude, Blink and you'll miss it, ...",\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
210,210,11,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,[Arlo Black],No relationships tagged,[Character Study],\n English\n,2023-05-26,Unknown,1129,1/1,12,67,2,461

In [61]:
print(type(candela_df))

<class 'pandas.DataFrame'>

In [62]:
print(len(candela_df))

211

In [63]:
candela_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   level_0           211 non-null    int64
 1   index             211 non-null    int64
 2   Rating            211 non-null    object
 3   Archive Warnings  211 non-null    object
 4   Category          211 non-null    object
 5   Fandom            211 non-null    object
 6   Characters        211 non-null    object
 7   Relationships     211 non-null    object
 8   Additional Tags   211 non-null    object
 9   Language          211 non-null    object
 10  Date Published    211 non-null    object
 11  Date Updated      211 non-null    object
 12  Word Count        211 non-null    object
 13  Chapter Count     211 non-null    object
 14  Comment Count     211 non-null    object
 15  Kudos Count       211 non-null    object
 16  Bookmarks Count   211 non-null    object
 17  Hits Count        211 non-null    object
dtypes: int64(2), object(16)
memory usage: 29.8+ KB

In [65]:
print("Shape of candela_df: " , candela_df.shape)

Shape of candela_df:  (211, 18)

In [ ]:
# characters - for each row, if the data type in characters is a list
# add a column to the dataframe with the info for each list item

In [66]:
candela_df['Characters'][0]

['Malcolm Trills', 'Leo Amicus', 'Grimoria (Candela Obscura)', 'Edgar Lycoris']

In [71]:
# get subset of dataframe
test_df = candela_df.iloc[0]

In [68]:
row1 = candela_df.iloc[0]

In [86]:
(candela_df.iloc[0]).to_frame().T

,level_0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"[Malcolm Trills, Leo Amicus, Grimoria (Candela...",Leo Amicus & Malcolm Trills,"[Team as Family, Team Dynamics, Affectionate I...",\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371

In [72]:
print(type(row1))

<class 'pandas.Series'>

In [77]:
test_df = row1.to_frame().T

In [78]:
print(type(test_df))

<class 'pandas.DataFrame'>

In [79]:
display(test_df)

,level_0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),"[Malcolm Trills, Leo Amicus, Grimoria (Candela...",Leo Amicus & Malcolm Trills,"[Team as Family, Team Dynamics, Affectionate I...",\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371

In [82]:
for i in range(len(test_df)):
    characters = test_df['Characters'][i]
    if type(characters) == list:
        character_df = pd.DataFrame()
        for index in range(len(characters)):
            character = characters[index]
            print(character)
            print(type(character))
            copy_df = test_df.copy()
            copy_df['Characters'] = character
            character_df = pd.concat([character_df, copy_df])
        # new_row = test_df.iloc(len(test_df))
        # print("Character type is a list")

Malcolm Trills
<class 'str'>
Leo Amicus
<class 'str'>
Grimoria (Candela Obscura)
<class 'str'>
Edgar Lycoris
<class 'str'>

In [83]:
print(character_df)

  level_0 index                 Rating           Archive Warnings Category  \
0       0     1  Teen And Up Audiences  No Archive Warnings Apply      Gen
0       0     1  Teen And Up Audiences  No Archive Warnings Apply      Gen
0       0     1  Teen And Up Audiences  No Archive Warnings Apply      Gen
0       0     1  Teen And Up Audiences  No Archive Warnings Apply      Gen

                                       Fandom                  Characters  \
0  Candela Obscura (Critical Role Web Series)              Malcolm Trills
0  Candela Obscura (Critical Role Web Series)                  Leo Amicus
0  Candela Obscura (Critical Role Web Series)  Grimoria (Candela Obscura)
0  Candela Obscura (Critical Role Web Series)               Edgar Lycoris

                 Relationships  \
0  Leo Amicus & Malcolm Trills
0  Leo Amicus & Malcolm Trills
0  Leo Amicus & Malcolm Trills
0  Leo Amicus & Malcolm Trills

                                     Additional Tags  \
0  [Team as Family, Team Dynamics, Affectionate I...
0  [Team as Family, Team Dynamics, Affectionate I...
0  [Team as Family, Team Dynamics, Affectionate I...
0  [Team as Family, Team Dynamics, Affectionate I...

                    Language Date Published Date Updated Word Count  \
0  \n        English\n           2024-03-07      Unknown       2506
0  \n        English\n           2024-03-07      Unknown       2506
0  \n        English\n           2024-03-07      Unknown       2506
0  \n        English\n           2024-03-07      Unknown       2506

  Chapter Count Comment Count Kudos Count Bookmarks Count Hits Count
0           1/1             8          61               4        371
0           1/1             8          61               4        371
0           1/1             8          61               4        371
0           1/1             8          61               4        371

In [87]:
for i in range(len(candela_df)):
    characters = candela_df['Characters'][i]
    if type(characters) == list:
        character_df = pd.DataFrame()
        current_row_df = (candela_df.iloc[0]).to_frame().T
        for index in range(len(characters)):
            character = characters[index]
            # print(character)
            # print(type(character))

            # get current row as dataframe
            current_row_df['Characters'] = character
            character_df = pd.concat([character_df, current_row_df])
        candela_df1 = pd.concat([candela_df, character_df])
    else:
        pass
    # candela_df1 = pd.concat([candela_df, character_df])
        # new_row = test_df.iloc(len(test_df))
        # print("Character type is a list")

In [88]:
print(len(candela_df1))

212

In [92]:
candela_df1.iloc[211].to_frame().T

,level_0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Arlo Black,Leo Amicus & Malcolm Trills,"[Team as Family, Team Dynamics, Affectionate I...",\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371

In [89]:
print(candela_df1.tail())

    level_0 index                 Rating           Archive Warnings Category  \
207     207     8               Explicit  No Archive Warnings Apply      F/M
208     208     9  Teen And Up Audiences  No Archive Warnings Apply      F/M
209     209    10  Teen And Up Audiences  No Archive Warnings Apply      F/M
210     210    11      General Audiences  No Archive Warnings Apply      Gen
0         0     1  Teen And Up Audiences  No Archive Warnings Apply      Gen

                                         Fandom  \
207  Candela Obscura (Critical Role Web Series)
208  Candela Obscura (Critical Role Web Series)
209  Candela Obscura (Critical Role Web Series)
210                             Candela Obscura
0    Candela Obscura (Critical Role Web Series)

                                            Characters  \
207  [Arlo Black (Candela Obscura), August James (C...
208  [Arlo Black (Candela Obscura), August "Auggie"...
209  [Arlo Black (Candela Obscura), Howard Margrove...
210                                       [Arlo Black]
0                                           Arlo Black

                                         Relationships  \
207                  August 'Auggie' James/ Arlo Black
208                   Arlo Black/August "Auggie" James
209  [Arlo Black & Howard Margrove, Arlo Black/Howa...
210                            No relationships tagged
0                          Leo Amicus & Malcolm Trills

                                       Additional Tags  \
207                                 [Ftm August James]
208  [Written post episode 2, First Kiss, Idk they ...
209  [missing interlude, Blink and you'll miss it, ...
210                                  [Character Study]
0    [Team as Family, Team Dynamics, Affectionate I...

                      Language Date Published Date Updated Word Count  \
207                    English        Unknown  03 Jul 2023       6125
208  \n        English\n           2023-07-02      Unknown       3378
209  \n        English\n           2023-06-26      Unknown       1082
210  \n        English\n           2023-05-26      Unknown       1129
0    \n        English\n           2024-03-07      Unknown       2506

    Chapter Count Comment Count Kudos Count Bookmarks Count Hits Count
207          None             9          83               8      1,259
208           1/1            48         332              49       1670
209           1/1             2          27               4        220
210           1/1            12          67               2        461
0             1/1             8          61               4        371

In [93]:
candela_df_exploded = candela_df.explode("Characters")

In [95]:
candela_df_exploded = candela_df_exploded.explode("Relationships")

In [97]:
candela_df_exploded = candela_df_exploded.explode("Archive Warnings")

In [100]:
candela_df_exploded = candela_df_exploded.explode("Fandom")

In [102]:
candela_df_exploded = candela_df_exploded.explode("Additional Tags")

In [103]:
display(candela_df_exploded)

,level_0,index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,1,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,10,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
210,210,11,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,\n English\n,2023-05-26,Unknown,1129,1/1,12,67,2,461

In [113]:
# get rid of index column
candela_df_exploded = candela_df_exploded.drop(columns=["index"])

In [114]:
display(candela_df_exploded)

,level_0,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
210,210,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,\n English\n,2023-05-26,Unknown,1129,1/1,12,67,2,461

In [115]:
# rename level_0 column to be index
candela_df_exploded = candela_df_exploded.rename(columns={"level_0": "Index"})

In [116]:
display(candela_df_exploded)

,Index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
210,210,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,\n English\n,2023-05-26,Unknown,1129,1/1,12,67,2,461

In [117]:
candela_df_exploded = candela_df_exploded.reset_index()

In [118]:
display(candela_df_exploded)

,index,Index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
1,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
2,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
3,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
4,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,\n English\n,2024-03-07,Unknown,2506,1/1,8,61,4,371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48346,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
48347,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
48348,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
48349,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,\n English\n,2023-06-26,Unknown,1082,1/1,2,27,4,220
48350,210,210,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,\n English\n,2023-05-26,Unknown,1129,1/1,12,67,2,461

In [119]:
print(candela_df_exploded['Language'][0])

        English

In [120]:
print(type(candela_df_exploded['Language'][0]))

<class 'str'>

In [124]:
print(type(candela_df_exploded['Language'][0]))

<class 'str'>

In [125]:
lang_string = candela_df_exploded['Language'][0]

In [126]:
print(lang_string)

        English

In [127]:
candela_df_exploded['Language'] = candela_df_exploded['Language'].replace(lang_string,'English')

In [128]:
display(candela_df_exploded)

,index,Index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count
0,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,English,2024-03-07,Unknown,2506,1/1,8,61,4,371
1,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,English,2024-03-07,Unknown,2506,1/1,8,61,4,371
2,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,English,2024-03-07,Unknown,2506,1/1,8,61,4,371
3,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,English,2024-03-07,Unknown,2506,1/1,8,61,4,371
4,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,English,2024-03-07,Unknown,2506,1/1,8,61,4,371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48346,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,English,2023-06-26,Unknown,1082,1/1,2,27,4,220
48347,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,English,2023-06-26,Unknown,1082,1/1,2,27,4,220
48348,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,English,2023-06-26,Unknown,1082,1/1,2,27,4,220
48349,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,English,2023-06-26,Unknown,1082,1/1,2,27,4,220
48350,210,210,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,English,2023-05-26,Unknown,1129,1/1,12,67,2,461

In [129]:
dates_published = candela_df_exploded['Date Published']

In [133]:
# figure out how many instances of 'Unknown' there are
# count_sravan = data['name'].value_counts().get('sravan', 0)
count_unknown = candela_df_exploded['Date Published'].value_counts().get('Unknown', 0)

In [134]:
print(count_unknown)

41367

In [135]:
count_unknown1 = candela_df_exploded['Date Updated'].value_counts().get('Unknown', 0)
print(count_unknown1)

3139

In [136]:
unique_date_updated = list(candela_df_exploded['Date Updated'].unique())
print(unique_date_updated)

['Unknown', '27 Feb 2024', '2024-02-25', '13 Feb 2024', '12 Feb 2024', '09 Feb 2024', '04 Feb 2024', '03 Feb 2024', '24 Jan 2024', '23 Jan 2024', '21 Jan 2024', '23 May 2024', '2024-05-14', '12 May 2024', '10 May 2024', '2024-05-04', '27 Apr 2024', '2024-04-24', '24 Apr 2024', '06 Apr 2024', '2024-03-12', '10 Oct 2023', '06 Oct 2023', '04 Oct 2023', '2023-10-03', '02 Oct 2023', '30 Sep 2023', '29 Sep 2023', '28 Sep 2023', '27 Sep 2023', '26 Sep 2023', '2023-09-25', '25 Sep 2023', '22 Sep 2023', '10 Sep 2023', '2023-09-09', '09 Sep 2023', '08 Sep 2023', '06 Sep 2023', '05 Sep 2023', '02 Sep 2023', '01 Sep 2023', '05 Aug 2023', '02 Aug 2023', '03 Jul 2023']

In [137]:
# convert date format to sthg else
test_date = unique_date_updated[1]
print(test_date)

27 Feb 2024

In [138]:
import dateparser

In [139]:
dateparser.parse(test_date)

datetime.datetime(2024, 2, 27, 0, 0)

In [152]:
for i in range(len(candela_df_exploded)):
    current_date_published = candela_df_exploded['Date Published'][i]
    if current_date_published != 'Unknown':
        date = dateparser.parse(current_date_published)
        # print(date)
        candela_df_exploded.loc[i, 'Date_Published'] = date
    else:
        pass

TypeError: Input type must be str

In [147]:
display(candela_df_exploded)

,index,Index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count,Date_Published
0,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,English,2024-03-07,Unknown,2506,1/1,8,61,4,371,2024-03-07
1,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,English,2024-03-07,Unknown,2506,1/1,8,61,4,371,2024-03-07
2,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,English,2024-03-07,Unknown,2506,1/1,8,61,4,371,2024-03-07
3,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,English,2024-03-07,Unknown,2506,1/1,8,61,4,371,2024-03-07
4,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura (Critical Role Web Series),Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,English,2024-03-07,Unknown,2506,1/1,8,61,4,371,2024-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48346,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,English,2023-06-26,Unknown,1082,1/1,2,27,4,220,2023-06-26
48347,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,English,2023-06-26,Unknown,1082,1/1,2,27,4,220,2023-06-26
48348,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,English,2023-06-26,Unknown,1082,1/1,2,27,4,220,2023-06-26
48349,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura (Critical Role Web Series),Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,English,2023-06-26,Unknown,1082,1/1,2,27,4,220,2023-06-26
48350,210,210,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,English,2023-05-26,Unknown,1129,1/1,12,67,2,461,2023-05-26

In [154]:
print(type(candela_df_exploded['Date Published'][12]))

<class 'datetime.datetime'>

In [158]:
print(type(candela_df_exploded['Date Updated'][207]))

<class 'datetime.datetime'>

In [159]:
print(candela_df_exploded['Date Updated'][207])

2024-02-27 00:00:00

In [161]:
# get unique fandom values
unique_fandoms = list(candela_df_exploded['Fandom'].unique())
print(unique_fandoms)

['Candela Obscura (Critical Role Web Series)', 'Critical Role (Web Series)', 'Candela Obscura']

In [162]:
candela_df_exploded['Fandom'] = candela_df_exploded['Fandom'].replace('Candela Obscura (Critical Role Web Series)','Candela Obscura')

In [163]:
candela_df_exploded['Fandom'] = candela_df_exploded['Fandom'].replace('Critical Role (Web Series)','Candela Obscura')

In [166]:
unique_fandoms1 = list(candela_df_exploded['Fandom'].unique())
print(unique_fandoms1)

['Candela Obscura']

In [167]:
# get unique fandom values
unique_characters = list(candela_df_exploded['Characters'].unique())
print(unique_characters)

['Malcolm Trills', 'Leo Amicus', 'Grimoria (Candela Obscura)', 'Edgar Lycoris', 'Grimoria', 'Decklan Murphy (Mentioned)', 'Leo Amicus (Mentioned)', 'Edgar Lycoris (Mentioned)', 'Sean Finnerty (Candela Obscura)', 'Marion Collodi', 'Nathaniel Trapp', 'Jinnah "Jean" Basar', 'Beatrix Monroe | Auntie Bee', 'Jimmy Finnerty (Candela Obscura)', 'Original Characters', 'Original Female Character(s)', 'Original', 'Elsie Roberts (Candela Obscura)', 'Oscar Grimm', 'Cosmo Grimm (Candela Obscura)', 'Cordelia Glask', "Godot | Cosmo Grimm's Dog (Candela Obscura)", 'Minor Characters', 'Magpie - Character', 'Rajan Savarimuthu', 'Mina (Candela Obscura)', 'Iomene (Candela Obscura)', '(mentioned)', 'Amadeus Porthos (OMC)', 'Godot (Candela Obscura)', 'Rajan Savarimuthu (Mentioned)', 'Cordelia Glask (Mentioned)', 'The Mother (Candela Obscura)', 'Zora Manning', 'Nokari (mentioned)', 'rpg character - Character', 'Mentioned Grimoria (Candela Obscura)', 'Mentioned Malcolm Trills', 'Mentioned Decklan Murphy (Candela Obscura)', 'Original Male Character(s)', 'Felix (Candela Obscura)', 'August "Auggie" James', 'Arlo Black (Candela Obscura)', 'Howard Margrove', 'Charlotte Eaves', "Alexandra Elise O'Neill (Candela Obscura)", 'Eddie Easton', 'The Foggs', 'lucas (Candela Obscura)', 'Margaret "Peggy" Finnerty (Candela Obscura)', 'Jinnah "Jean" Basar (Briefly)', 'Sean Finnerty', 'Tony Finnerty (Candela Obscura)', 'Violet Boucher', 'ish - Character', 'Tony Finnerty', 'Jimmy Finnerty', 'Dr. Jinnah "Jean" Basar', 'Nathaniel Trapp (Mentioned)', 'Field Officer Aaron Weimer', "Arlo's Father", "Arlo Black's Father (Candela Obscura)", 'Alexandra (Candela Obscura)', 'Eddie(mentioned)', 'Dean (Candela Obscura)', "Arlo Black's Father", 'Charlotte and Howard are only mentioned', 'August James (Candela Obscura)', 'Howard Margrove (Candela Obscura)', 'Arlo Black']

In [173]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Original','Original Characters')

In [175]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Original Female Character(s)', 'Original Characters')

In [176]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Original','Original Characters')

In [177]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Original Male Character(s)', 'Original Characters')

In [179]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Sean Finnerty (Candela Obscura)', 'Sean Finnerty')

In [180]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Jimmy Finnerty (Candela Obscura)', 'Jimmy Finnerty')

In [182]:
candela_df_exploded['Characters'] = candela_df_exploded['Characters'].replace('Elsie Roberts (Candela Obscura)', 'Elsie Roberts')

In [170]:
# update character stuff
for i in range(len(candela_df_exploded)):
    chapter_count_current = candela_df_exploded['Chapter Count'][i]
    print(chapter_count_current)
    current_date_updated = candela_df_exploded['Date Updated'][i]
    current_date_published = candela_df_exploded['Date Published'][i]
    if chapter_count_current == '1/1' and current_date_updated == 'Unknown':
        candela_df_exploded.loc[i, 'Date Updated'] = current_date_published
    else:
        pass

1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
1/1
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None

In [171]:
display(candela_df_exploded)

,index,Index,Rating,Archive Warnings,Category,Fandom,Characters,Relationships,Additional Tags,Language,Date Published,Date Updated,Word Count,Chapter Count,Comment Count,Kudos Count,Bookmarks Count,Hits Count,Date_Published
0,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Malcolm Trills,Leo Amicus & Malcolm Trills,Team as Family,English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371,2024-03-07
1,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Malcolm Trills,Leo Amicus & Malcolm Trills,Team Dynamics,English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371,2024-03-07
2,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Malcolm Trills,Leo Amicus & Malcolm Trills,Affectionate Insults,English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371,2024-03-07
3,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Malcolm Trills,Leo Amicus & Malcolm Trills,Veterans,English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371,2024-03-07
4,0,0,Teen And Up Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Malcolm Trills,Leo Amicus & Malcolm Trills,Pre-Canon,English,2024-03-07 00:00:00,2024-03-07 00:00:00,2506,1/1,8,61,4,371,2024-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48346,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura,Howard Margrove (Candela Obscura),Arlo Black & Howard Margrove,but the deserve to be soft,English,2023-06-26,2023-06-26,1082,1/1,2,27,4,220,2023-06-26
48347,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura,Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,missing interlude,English,2023-06-26,2023-06-26,1082,1/1,2,27,4,220,2023-06-26
48348,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura,Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,Blink and you'll miss it,English,2023-06-26,2023-06-26,1082,1/1,2,27,4,220,2023-06-26
48349,209,209,Teen And Up Audiences,No Archive Warnings Apply,F/M,Candela Obscura,Howard Margrove (Candela Obscura),Arlo Black/Howard Margrove,but the deserve to be soft,English,2023-06-26,2023-06-26,1082,1/1,2,27,4,220,2023-06-26
48350,210,210,General Audiences,No Archive Warnings Apply,Gen,Candela Obscura,Arlo Black,No relationships tagged,Character Study,English,2023-05-26,2023-05-26,1129,1/1,12,67,2,461,2023-05-26

In [183]:
# save dataframe to csv file
path_to_save = '/data/candela_df_exploded.csv'
candela_df_exploded.to_csv(path_to_save)